Build and push images

diff --git a/.github/workflows/build-backend.yaml b/.github/workflows/build-backend.yaml
--- a/.github/workflows/build-backend.yaml
+++ b/.github/workflows/build-backend.yaml
@@ -34,7 +34,7 @@ jobs:
     steps:
       - id: init
         name: Init Workflow
-        uses: hawk-ai-aml/github-actions/workflow-init@master
+        uses: hawk-ai-aml/github-actions/workflow-init@build-backend
         with:
           profile: ${{ inputs.profile }}
           component: ${{ inputs.component }}
@@ -68,37 +68,39 @@ jobs:
         run: ./gradlew clean assemble testClasses -isS
 
       - name: License Report
-        run: ./gradlew licenseReport
+        run: ./gradlew licenseReport --no-parallel
 
       - name: Check Quality
         run: ./gradlew checkQualityMain
 
       - name: Run Tests
         if: ${{ needs.init.outputs.skip-tests != 'true' }}
-        run: ./gradlew check -isS
-
-      - name: Upload Reports to S3
-        id: reports
-        if: success() || failure()
-        uses: hawk-ai-aml/upload-s3-action@master
-        with:
-          aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
-          aws_bucket: github-actions-static-html-2
-          source_dir: app/build/reports
-          destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
-
-      - name: Provide Links to Reports
-        if: success() || failure()
         run: |
-          echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
-          report_url=https://github-actions-static-html-2.s3.amazonaws.com/${{ github.event.repository.name }}-${{ github.run_id }}/
-          for report_file_loc in ${{ join(fromJSON(steps.reports.outputs.object_locations), ' ') }}; do
-            report_basename=${report_file_loc##${report_url}}
-            if [[ ${report_file_loc} == */main.html || ${report_file_loc} == */index.html || ${report_file_loc} == */licenseReport.html ]]; then
-              echo "* [${report_basename}](${report_file_loc})" | tee -a ${GITHUB_STEP_SUMMARY}
-            fi
-          done
+          ./gradlew check -isS
+          ./gradlew aggregateJacocoExecutions
+
+      # - name: Upload Reports to S3
+      #   id: reports
+      #   if: success() || failure()
+      #   uses: hawk-ai-aml/upload-s3-action@master
+      #   with:
+      #     aws_key_id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
+      #     aws_secret_access_key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
+      #     aws_bucket: github-actions-static-html-2
+      #     source_dir: ./
+      #     destination_dir: ${{ github.event.repository.name }}-${{ github.run_id }}
+
+      # - name: Provide Links to Reports
+      #   if: success() || failure()
+      #   run: |
+      #     echo "### Test Reports" | tee -a ${GITHUB_STEP_SUMMARY}
+      #     report_url=https://github-actions-static-html-2.s3.amazonaws.com/${{ github.event.repository.name }}-${{ github.run_id }}/
+      #     for report_file_loc in ${{ join(fromJSON(steps.reports.outputs.object_locations), ' ') }}; do
+      #       report_basename=${report_file_loc##${report_url}}
+      #       if [[ ${report_file_loc} == */main.html || ${report_file_loc} == */index.html || ${report_file_loc} == */licenseReport.html ]]; then
+      #         echo "* [${report_basename}](${report_file_loc})" | tee -a ${GITHUB_STEP_SUMMARY}
+      #       fi
+      #     done
 
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
@@ -116,27 +118,26 @@ jobs:
       - name: Build image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
         run: |
           ./gradlew build -Dskip.tests=true -x test
-          ./gradlew jibDockerBuild -DIMAGE_NAME="${ECR_REGISTRY}/${ECR_REPOSITORY}" -DTAG_COMMIT=${{ env.HAWK_IMAGE_TAG }}
+          ./gradlew jib -DIMAGE_NAME="${ECR_REGISTRY}/" -DTAG_COMMIT=${{ env.HAWK_IMAGE_TAG }}
 
-      - name: Push Image
-        id: push-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
-        run: |
-          export DOCKER_CLI_EXPERIMENTAL=enabled
+      # - name: Push Image
+      #   id: push-image
+      #   env:
+      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+      #     ECR_REPOSITORY: ${{ fromJson(needs.init.outputs.metadata).ecr.repository }}
+      #   run: |
+      #     export DOCKER_CLI_EXPERIMENTAL=enabled
 
-          set +e
-          docker manifest inspect ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }} 2>&1> /dev/null
-          inspect_code=$?
-          set -e
+      #     set +e
+      #     docker manifest inspect ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }} 2>&1> /dev/null
+      #     inspect_code=$?
+      #     set -e
 
-          if [[ "${inspect_code}" != 0 ]]; then  
-            docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
-          fi
+      #     if [[ "${inspect_code}" != 0 ]]; then  
+      #       docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ env.HAWK_IMAGE_TAG }}
+      #     fi
 
   update-overlays:
     needs: [ init, build ]
